# Use the official Node.js image as the base image
FROM node:18.7.0

# Set the working directory in the container
WORKDIR /src/

# Copy the backend source code to the container
COPY ../package*.json ./


# Install backend dependencies
COPY . .
RUN npm install


# Expose the port your backend application will run on
EXPOSE 3000

# Start the backend server
CMD ["npm", "server"]

